// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QrCode.Models;

#nullable disable

namespace QrCode.Migrations
{
    [DbContext(typeof(QrCodeContext))]
    [Migration("20230927013013_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QrCode.Models.Pengunjung", b =>
                {
                    b.Property<int>("IdPengunjung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPengunjung"));

                    b.Property<string>("Jabatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kantor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPengunjung");

                    b.ToTable("Pengunjung");
                });

            modelBuilder.Entity("QrCode.Models.Stasiun", b =>
                {
                    b.Property<int>("IdStasiun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStasiun"));

                    b.Property<string>("NamaStasiun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStasiun");

                    b.ToTable("Stasiun");
                });
#pragma warning restore 612, 618
        }
    }
}
